project:
  type: website
  output-dir: docs

website:
  title: "PhD Progress Log"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: progress-reports.qmd
        text: Progress Reports
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/Jody-Holland
      - icon: search
    website:
  # ... your existing config
  page-footer: 
    left: "© 2025 Jody Holland"
    center: "PhD Progress Log"

format:
  html:
    theme: [minty, flatly, cosmo] 
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-link: true
    
  pdf:
    documentclass: article
    papersize: a4
    fontsize: 11pt
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=2.5cm
      - right=2.5cm
    toc: false
    number-sections: true
    linestretch: 1.25
    
  docx:
    toc: false
    number-sections: true